package com.malak.task3;

//import java.util.ArrayList;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
//import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
//import org.springframework.validation.BindingResult;
//import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
//import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
//import org.springframework.web.servlet.ModelAndView;





@Controller
public class PersonConroller {
	@Autowired
	private PersonService service;
	//text generated by the controller
	@ResponseBody
	@GetMapping("/ControllText")
	public String getTextGeneratedByTheController() {
		
		return "This is a text generated by the controller";
	}
	
	//view the form Add Person
	@GetMapping("/personForm")
	public String getForm() {
		
		return "PersonForm";
	}
	
	//the post method when submitting the Form
	@PostMapping("/FormSubmission")
	public String submitForm(@ModelAttribute("person1") Person person1) {
		
		service.savePerson(person1);
		
		
		return "PersonForm";
	}
	
	@GetMapping("/")
	public String getPersonList(ModelMap model){
		List<Person> personList=service.getPeople();
		
		model.put("personList", personList);
	  return "PersonTable";
		
	}
	

	
	

}
